theme: jekyll-theme-cayman
title: Epiphane Loko
description: GIPSA Lab, Université Grenoble Alpes | dagbegnon-epiphane.loko@gipsa-lab.grenoble-inp.fr
description: 11 Rue des Mathématiques, 38400 Saint-Martin-d'Hères, France, Office B227
show_downloads: false
google_analytics:
