theme: jekyll-theme-minimal
title: Epiphane Loko
description: >-
  PhD Candidate in Control Theory | CERMICS, Ã‰cole des Ponts & L2S, Paris-Saclay University

# Activer/DÃ©sactiver le bouton de tÃ©lÃ©chargement sur GitHub Pages
show_downloads: false

# Menu de navigation
menu:
  - "[ğŸ”— About Me](#about-me)"
  - "[ğŸ† Awards](#awards)"
  - "[ğŸ“š Research Publications](#research-publications)"
  - "[ğŸ¤ Academic Talks](#academic-presentations-and-talks)"
  - "[ğŸ‘¨â€ğŸ« Teaching Experience](#teaching-experience)"
  - "[ğŸ“„ CV](https://github.com/user-attachments/files/18690641/CV_Epiphane.pdf)"
