title: Hacker theme
description: Hacker is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
title: Epiphane Loko
description: CERMICS, Ã‰cole nationale des ponts et chaussÃ©es & L2S, Paris-Saclay University | dagbegnon.loko@enpc.fr

# Activer/DÃ©sactiver le bouton de tÃ©lÃ©chargement sur GitHub Pages
show_downloads: false

# Menu de navigation
menu:
  - "[ğŸ”— About Me](#about-me)"
  - "[ğŸ† Awards](#awards)"
  - "[ğŸ“š Research Publications](#research-publications)"
  - "[ğŸ¤ Academic Talks](#academic-presentations-and-talks)"
  - "[ğŸ‘¨â€ğŸ« Teaching Experience](#teaching-experience)"
  - "[ğŸ“„ CV](https://github.com/user-attachments/files/18690641/CV_Epiphane.pdf)"
